### ISSUE TITLE
Request for repository removal

### ISSUE THREAD

**Issue by theofficialgman** [Lemonade-emu/Lemonade#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The citra developers have expressed extreme disapproval for this repositories actions.
The continued licence violations from this repository show that the maintainers are incapable of supporting their own project legally. https://github.com/Lemonade-emu/Lemonade/issues/100 https://github.com/Lemonade-emu/Lemonade/issues/97
I am requesting that Lemonade be disbanded and removed.

### Why would this feature be useful?

Lemonade removal would benefit prior and new citra users.

It brings the community back together under one project maintained by and developed by the actual code authors.

It reduces confusion where this project claims to be a successor of citra when in fact that project has not ended but instead moved to new ownership under the same name.

**Comment by Thesamman23** [comment]
i don't know about that but it would be cool if they fixed the repo. i wouldn't go that far as to destroy the whole project. that would be a little silly. just fix it

**Comment by Ishan09811** [comment]
first of all whatever issues you showed is not from official Citra emu dev.

**Comment by Polarzincomfrio** [comment]
just closing this, is effectively just "throwing the problem under the rug" your image has already been tarnished and yet you still ask your users to stop talking about the problem instead of even trying to fix the clear issue in the room

**Comment by Ishan09811** [comment]
@theofficialgman 
ahh this issue is request to remove the project and you are telling to do this?

**Comment by cobalt2727** [comment]
Saying it was "just two commits and not the whole emulator" is a factually incorrect statement as long as https://github.com/Lemonade-emu/Lemonade/commit/9289b445f949eb8b03e5192956d755271f4057b8 exists. Please stop repeating it.

**Comment by theofficialgman** [comment]
This request I made was in hopes that you would comply peacefully.

Your refusal to stop committing copyright infringement and not remove the repo now gives any user authority to submit a DMCA takedown request of this repository. Expect to get one within a few days.

**Comment by BlurrySquire** [comment]
> first of all whatever issues you showed is not from official Citra emu dev and We haven't deleted the commit history and why would we? btw this is the same repo used for `citra-enhanced` because we had to make an initial commit to switch it to the latest `citra-canary` code but the commit history is gone. but we will try to recover the commit history. and We also want to say that we always credit people on our releases. But Pablo wanted to get credited on commits, and it's fine. We talked with him and we will always credit him on commits.
> 
> They also were 2 commits, not the whole emulator. The rest of our project was made ourselves. (You can compare both projects yourself).

You say you haven't deleted the commit history and then said the commit history is gone.  What you are saying about the commit history it goes back on itself. If you didn't delete the commit history then how is it gone? Crediting on releases isn't how GPLv2 works. You must credit the moment you take their code.

Also it wasn't 2 commits, Most of the code was produced by the citra organisation. It is uncredited because all the commit history for their work is gone. You should of forked the actual Citra repo not someone else's fork which is outdated, because then you don't have to commit the new source code (in a single commit) without commit history. There probably is no way of recovering that commit history. You would have to start from scratch, fork a citra backup fork and rebrand everything again and add the features you previously added. Your codebase was a mess, it's forked from a repo that it isn't even using as a base. Also, why are like half the commits just named 'bonk'.

**Comment by Litbolt123** [comment]
So from what I am hearing, I might have to go to a diff 3ds emu (Lime, Pablomk7s, etc.) for now until this gets resolved or Lemonade remakes itself from scratch?

**Comment by Polarzincomfrio** [comment]
> So from what I am hearing, I might have to go to a diff 3ds emu (Lime, Pablomk7s, etc.) for now until this gets resolved or Lemonade remakes itself from scratch? 

i would advise you to go to Lime or to Pablomk7's fork, Lemonade is under many controversies rn and by the looks of it, with the devs not being responsible, looks like Lemonade will be shutdown, before or after a dmca
