### ISSUE TITLE
PabloMK7/citra GPL license violation

### ISSUE THREAD

**Issue by PabloMK7** [Lemonade-emu/Lemonade#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

N/A

### Description of Issue

The following commit is violating PabloMK7/citra's GPL license as it is not properly crediting the original authors:
a245d300e03be1f87bfb787a6ad0dc08ba8bb4a9

It is requested to respect the GPL license of PabloMK7/citra and refrain from breaking the license again in the future.

### Expected Behavior

N/A

### Reproduction Steps

N/A

### Log File

N/A

### System Configuration

N/A

**Comment by Ishan09811** [comment]
@PabloMK7 
ahh don't tell me you are serious

**Comment by PabloMK7** [comment]
> @PabloMK7 ahh don't tell me you are serious

Yes, I am. Without proper credits this is stolen code.

**Comment by kleidiss** [comment]
> > @PabloMK7 ahh don't tell me you are serious
> 
> Yes, I am. Without proper credits this is stolen code.

We credit people on releases if we have taken code from them , this commit hasn't made the release yet, But if you want to we can credit you in the readme

**Comment by kleidiss** [comment]
Just reply to me to know that you're ok with your name being on the readme, some ppl wouldnt want that

**Comment by PabloMK7** [comment]
As soon as a commit goes into the master branch without crediting, the license is being broken.

We can make a compromise if you make sure to at least have proper crediting from now on if a commit comes from another repository.

**Comment by kleidiss** [comment]
> As soon as a commit goes into the master branch without crediting, the license is being broken.
> 
> We can make a compromise if you make sure to at least have proper crediting from now on if a commit comes from another repository.

Ok than, we'll use a merger next time we take a commit out of your or any other repo and you will be credited more appropriately , @Gamer64ytb please follow this from now on,

**Comment by Ishan09811** [comment]
@PabloMK7 
but don't open a issue for these things when it is specially for application related issues, even if you want to talk about these things then you can do by joining our server and contacting the team members instead of opening issue for it.

**Comment by cobalt2727** [comment]
I'd like to have this issue reopened, actually - this commit https://github.com/Lemonade-emu/Lemonade/commit/9289b445f949eb8b03e5192956d755271f4057b8 has the same problem. This is absolutely **_not_** how you initialize a git repo.

Considering this is coming from a former MMJR manager I can't say I'm surprised (you have a history of pushing commits with tens of thousands of lines of other people's work, and I'd have a great example [if this repo hadn't been taken offline](https://github.com/Bankaimaster999/Dolphin-MMJR/commit/f053974cd266bc49bfefb82d34cfd15816e8ac0f)), but I'm still disappointed, considering this is a project trying to be a spiritual successor to Citra.

I'd definitely suggest fixing this as soon as possible, because the longer you put it off, the harder it is to clean up.

**Comment by dxgldotorg** [comment]
Wouldn't adding credit solve the issue?

**Comment by kleidiss** [comment]
> Wouldn't adding credit solve the issue?

Only the commit submitter can do that before the commit is added
They are just gonna rework this repository from scratch

**Comment by cobalt2727** [comment]
Yeah, that honestly looks like it might be the easiest fix at this point. This repo is listed as a fork of a defunct semi-official Citra fork back when Android was still a "new" platform...

**Comment by fearit** [comment]
> @PabloMK7 ahh don't tell me you are serious

petty thief
